### ISSUE TITLE
modalの作成

### ISSUE THREAD

**Issue by KenSato0527** [b1017173/Hometoku#1]
**作ろうとしている機能の詳細**
ゴール： Block Kit Builderを用いて，入力項目を完備したモーダル作成を目的とする
プロセス： 
1. モックアップの作成(slackの画像です)
2. Block Kit Builderの使い方について
2. 褒めたい人
3. 褒めたいこと
4. 褒めたい度(連打ボタン含む)
5. キャンセル右上(誤タップ防止のため)
6. 送信，取り消しボタン

**完成の定義**
バグの精査(入り込みそうなバグ)： 
1. 正しい質問項目
2. Submit を押すと入力が action preview に反映されているかどうか
3. Submit を押すとボタンタップ回数が action preview に反映されるかどうか
4. モックアップと一緒！
5. 完成したPayloadの jsonファイルをHometokuの直下に/dataを作成し，modal.jsonとして作成

**見積もり**
[1 d/人]  

**その他**
***作業ブランチ***
main - develop - issue01
***特筆事項***

****タスク作成者への注意事項****
1. タグ管理をしっかりやってほしいです。上のタスクを例にとると："優先度B", "feat(or 機能)", "search(or 検索)", "form(or 入力フォーム)"くらいは最低限つけてほしい。  
2. このカードの存在を忘れないで(T . T)  
    作ったタスクは移動すべきタイミングでカラムを移動し、最後まで見守りましょう。
3. 作業ブランチを切って，ブランチ名はイシュー名にする．
    ex)issue23 , issue33 とか

**Comment by b1017173** [comment]
Block Kit Builder : https://app.slack.com/block-kit-builder/

**Comment by b1017173** [comment]
step. 1 : モックアップの検討 
![image](https://user-images.githubusercontent.com/43740965/122056386-80cd1300-ce24-11eb-8ca7-5c4a7439eebe.png)

**Comment by KenSato0527** [comment]
<img width="508" alt="スクリーンショット 2021-06-17 19 12 09" src="https://user-images.githubusercontent.com/50400555/122377485-17720f00-cfa0-11eb-97df-65d4ab3dafd0.png">
原型．ボタンをクリックしても何もならないのは考えもの

**Comment by KenSato0527** [comment]
<img width="475" alt="スクリーンショット 2021-06-17 19 10 57" src="https://user-images.githubusercontent.com/50400555/122377624-32dd1a00-cfa0-11eb-818f-46f0981a66d7.png">
block_idを追加しない名前がランダムで帰ってくるそうなので勝手にmodalに付け足し(homePeople,homeMove)
<img width="628" alt="スクリーンショット 2021-06-17 19 10 19" src="https://user-images.githubusercontent.com/50400555/122377729-46888080-cfa0-11eb-8a72-b04ca0c0fa03.png">

**Comment by KenSato0527** [comment]
<img width="508" alt="スクリーンショット 2021-06-17 19 30 32" src="https://user-images.githubusercontent.com/50400555/122380345-bbf55080-cfa2-11eb-9448-15a633af7cae.png">
現在のmodal

**Comment by KenSato0527** [comment]
<img width="508" alt="スクリーンショット 2021-06-17 22 11 48" src="https://user-images.githubusercontent.com/50400555/122403181-22856900-cfb9-11eb-9641-e691f891dcd3.png">
とりあえずボタン連打はわからなかったのでradio buttonで実装．
ボタン1つにしようかとも思ったが，ボタンは2つ以上の項目でなければいけないらしく，
ただひとつだけのボタンが作れなかった．(例えば yes no のボタンを横に2つ配置するとかじゃないと返り値がなくなる)

妥協案のこの形の実装

**Comment by KenSato0527** [comment]
<img width="508" alt="スクリーンショット 2021-06-17 22 16 41" src="https://user-images.githubusercontent.com/50400555/122404642-5d3bd100-cfba-11eb-89a0-7e9f7459d6ac.png">

終了

**Comment by KenSato0527** [comment]
<img width="508" alt="スクリーンショット 2021-06-18 0 18 04" src="https://user-images.githubusercontent.com/50400555/122425819-ba3f8300-cfca-11eb-8388-fc913dc9bede.png">

ボタン実装終了
→ボタンが押されたら変数+1してformのjsonをもう一度送りつけて表示(今までの内容は保存しながら)
→表示の仕方はこたがやってるのでそっちを進めてコピペする予定
