### ISSUE TITLE
メッセージに表示するランダムなポジティブワードの洗い出し

### ISSUE THREAD

**Issue by tkeita1024** [b1017173/Hometoku#19]
**作ろうとしている機能の詳細**
ゴール： Message previewに表示される、ポジティブワードを少なくとも20種類考える。
プロセス： 
1. ポジティブワードの案を洗い出す。
2. 他の人にレビューしてもらう。
3. 1.2を繰り返し、みんながいいと思いったものを決める。

**完成の定義**
バグの精査(入り込みそうなバグ)： 
1. 案がダサい。
2. みんなのokをもらう。
3. 20種類以上の案がある。

**見積もり**
1日

**その他**
***作業ブランチ***
main - develop - issue15
***特筆事項***

****タスク作成者への注意事項****
1. タグ管理をしっかりやってほしいです。上のタスクを例にとると："優先度B", "feat(or 機能)", "search(or 検索)", "form(or 入力フォーム)"くらいは最低限つけてほしい。  
2. このカードの存在を忘れないで(T . T)  
    作ったタスクは移動すべきタイミングでカラムを移動し、最後まで見守りましょう。
3. 作業ブランチを切って，ブランチ名はイシュー名にする．
    ex)issue23 , issue33 とか

**Comment by tkeita1024** [comment]
ver1.0

手紙が届いていますよ、ホメル便が届いています、誰かが噂しています、ホーメル賞を受賞したよ、宇宙からホメ電波を受信したよ、誰かが褒めているよ、穴を掘っていたら何か見つけたよ、空から何か降ってきたみたいだ、スーパーの福引きでホメトク賞が当たったよ、ホメールガチャで何か当たったみたいだ、犬が何かを咥えているみたいだ、ジャングルにホメール文明の石碑があったよ、ホメトクフェスティバルが開催しているよ、ホメール神からの啓示を受けたよ、サンタさんからプレゼントをもらったよ、お褒め玉をもらったよ、TVでホメトークがやっているよ、不在通知が届いているよ、誰かが呼でいるよ、Hometterのメッセージが来ているよ、宝のありかが地図を見つけたよ、探しに行こう、

**Comment by tkeita1024** [comment]
ver1.1 

手紙が届いていますよ、ホメル便が届いています、誰かが噂しています、宇宙からホメ電波を受信したよ、応援メッセージが届いているよ、良いニュースがあるよ、Slackネーム匿名さんからお便りが来ています、見に行きましょう、

**Comment by b1017173** [comment]
手紙：3
ホメる便(宅配物)：0
噂話：2
ホメる賞：2
宇宙通信：1
褒め話：3
タイムカプセル：3
伝書鳩：2
福引：0
ガチャ：0
ここほれわんわん：2
石碑：3
フェスティバル：0
啓示(ホメール神が喜んでた的な)：2
サンタ(いい子にしてたから誰かがサンタに頼んだよ的な)：3
お年玉：0
テレビ：2
非通知留守電：2
呼んでるよ：0
メンバーの褒めツイがバズった：3
宝：0
ラジオ：3

**Comment by KenSato0527** [comment]
手紙，噂話，表彰，botに頼んで投稿してもらう，タイムカプセル，伝書鳩，ここほれわんわん，石碑，ホメール神が感動してたよ，良い子にしてたからサンタさんが持ってきたよ，ホメトークのほめたい芸人にチームメンバーが，非通知留守電，３万リツイート，ラジオ，

**Comment by KenSato0527** [comment]
※ hp : 褒められた人，--hm-- : 内容
1.手紙
　hpさんへ
　--hm--
　匿名さんより

2.噂話
　hpの素晴らしい活躍の噂話を聞きました！--hm--らしいですよ！

3.表彰
　hp様．--hm--という素晴らしい功績を残したため，チームメンバーよりここに賞する．

4.botに頼んで投稿してもらう
　シャイなチームメンバーから代わりにhpをホメてって言われちゃった！「--hm--」だって！凄いや！

5.タイムカプセル
　チームメンバーとタイムカプセルを掘りに行ったよ！hp宛に「--hm--」と書いてあったよ！

6.伝書鳩
　伝書鳩がhp宛にホメッセージを届けてきたよ！「--hm--」と書いてあったよ！

7.ここほれわんわん
　うちの犬が木の下で吠えててうるさい！もしかしてと思って掘ったら黄金のホメッセージが出てきたよ！
　「--hm--」って書いてあったよ！

8.石碑
　ホメール文明の石碑にhp宛の褒メッセージが記されている！どれどれ...「--hm--」だって！
　文化遺産だね！

9.ホメール神
　ホメール神がhpの「--hm--」という善行に感動してたよ！

10.サンタさん
　hpがいい子にしてたからサンタさんがプレゼント用意してたよ！「--hm--」というのを見ていたんだって！

11.ホメトーク
　チームメンバーがホメトークのホメたい芸人でhpをホメていたよ！「--hm--」というのを楽しそうに話していたよ！

12.非通知留守電
　お出かけしていたら僕のところに非通知留守電が...怖いけど聞いてみよう...
   hpへ「--hm--」
　全然怖くないじゃん！

13.3万リツイート
　hpの「--hm--」ということをこっそりツイートしたら3万リツイートいっちゃったよ！
　バズったからホメとく宣伝してきていいかな？
　
14.ラジオ
　始まりましたFMホメリアン！今日もホメッセージが届いております！
　ラジオネーム : ホメラニアンさんからhpさん宛に--hm--と届いておりました！

**Comment by KenSato0527** [comment]
15.やまびこ
　奥の山からhpへ「--hm--」って聞こえてきました！やまびこのせいで3倍ホメられてたよ！

16.ホメ履歴
　チームメンバーのパソコンに書きかけのホメッセージが残っていたよ！代わりに僕がホメちゃおう！
　「--hm--」
　次は顔を見てホメられるといいね！

17.air drop
　近くの人がhp宛にAirDropでホメッセージを送ってきたよ！「--hm--」
　他の人も拾わないように早く切ってね！

18.wifi
　チームメンバーがwifiの名前をhpにして，パスワードを「--hm--」にしちゃったよ！気持ちが溢れすぎたね！

19.オーダーメイドTシャツ
　こないだの土曜日，チームメンバーが「hpさんへ，--hm--．ありがとう」って背中に書いてあるTシャツを着て外を歩いていたよ！もうそれ直接言った方が恥ずかしくないと思うよ！

20.ブルーインパルス
　チームメンバーがブルーインパルスにお願いして「hpさんへ，--hm--」って書いてもらってたよ！よく協力してもらえたね！

**Comment by KenSato0527** [comment]
21. 花火
　花火大会で「hpへ，--hm--」と書いた10寸玉が上がってたよ！
