### ISSUE TITLE
アイコンの作成

### ISSUE THREAD

**Issue by tkeita1024** [b1017173/Hometoku#3]
**作ろうとしている機能の詳細**
ゴール：アイコンを作成する
プロセス： 
1. デザインのコンセプトを決める
2. イメージカラーを決める。
3. アイコンの案をいくつか担当者が出す。
4. いくつかの案の中で一番いいアイコンを投票で決める。
5. powerpointやillustratorなどのツールを用いてアイコンを作成する。
6. Slack Appのアイコンを作成したアイコン画像に差し替える。

**完成の定義**
バグの精査(入り込みそうなバグ)： 
1. みんなが納得するアイコンを作成する。
2. Slack Appのアイコンが作成したアイコンに変わっている。
3. Hometoku/data/image/icon.pngに保存する。

**見積もり**
[3日]  

**その他**
***作業ブランチ***
main - develop - issue03
***特筆事項***

****タスク作成者への注意事項****
1. タグ管理をしっかりやってほしいです。上のタスクを例にとると："優先度B", "feat(or 機能)", "search(or 検索)", "form(or 入力フォーム)"くらいは最低限つけてほしい。  
2. このカードの存在を忘れないで(T . T)  
    作ったタスクは移動すべきタイミングでカラムを移動し、最後まで見守りましょう。
3. 作業ブランチを切って，ブランチ名はイシュー名にする．
    ex)issue23 , issue33 とか

**Comment by b1017173** [comment]
Slack app icon のデザインガイド : https://api.slack.com/start/distributing/guidelines

**Comment by b1017173** [comment]
![IMG_5501](https://user-images.githubusercontent.com/43740965/122751259-7b5f4500-d2ca-11eb-879e-7c127a4e8e8e.jpg)

**Comment by b1017173** [comment]
アイコンできたぞーーーーーーー！！！！
![hometoku_icon_novia](https://user-images.githubusercontent.com/43740965/123978878-2f637d00-d9fb-11eb-944c-39050669909f.PNG)
![hometoku_icon_via](https://user-images.githubusercontent.com/43740965/123978897-34283100-d9fb-11eb-9ee4-fd2a1c86f7c4.PNG)
