### ISSUE TITLE
発表資料作成

### ISSUE THREAD

**Issue by Kai-Moriuchi** [b1017173/Hometoku#4]
**作ろうとしている機能の詳細**
ゴール： ハッカソン当日の発表内容を考えてスライドを作成する（発表時間は3分）
プロセス： 
1.発表したいことを洗い出す（これは絶対伝えたい！って内容等）
2.発表の大まかな流れ（トピック的なもの）を作成（Google Document等で）
3.トピックに沿った詳しい内容を記述
4.スライドのデザインを考える
5.スライドマスターの作成（Google Slideで）
6.Google Documentに記述した内容をスライドに反映

**完成の定義**
バグの精査(入り込みそうなバグ)： 
1. デザインの統一感がある
2. 3分に収まる
3. 内容がわかりやすい（難しい言葉とかがない）
4. Google Slideのアクセス権限が「リンクを知っている人」になっている

**見積もり**
5 h/人 

**その他**
***作業ブランチ***
SlackでGoogle Slideのリンクを共有
***特筆事項***

****タスク作成者への注意事項****
1. タグ管理をしっかりやってほしいです。上のタスクを例にとると："優先度B", "feat(or 機能)", "search(or 検索)", "form(or 入力フォーム)"くらいは最低限つけてほしい。  
2. このカードの存在を忘れないで(T . T)  
    作ったタスクは移動すべきタイミングでカラムを移動し、最後まで見守りましょう。
3. 作業ブランチを切って，ブランチ名はイシュー名にする．
    ex)issue23 , issue33 とか

**Comment by Kai-Moriuchi** [comment]
参加者のしおり
https://docs.google.com/document/d/1FoT4iwb-fpDW6eWnSiMlb3GPkLmWA1kwcEHAu15G6es/edit

**Comment by tkeita1024** [comment]
構成
- タイトル
- 動機
- 作品の紹介（動画？デモ？）
- アピールポイント
- 使用技術
- 締め

絶対に伝えたいこと
- ほめトクはどう開発効率化に役立つのか？

**Comment by tkeita1024** [comment]
タイトルについて
- ロゴを使用する
- ホメとくを入れる
- サブタイトルを入れる
  - 匿名ほめあいbot的な

**Comment by tkeita1024** [comment]
背景
- チーム開発を対象に開発効率化するために必要なことを考えた。
- 開発効率化のためにチームビルディングに着目した。
- チームビルディングには人間関係が大事。
- 人間関係を良くするためには、コミュニケーションが大事。
- コミュニケーションを円滑に行うためには、。
- 尊重するために褒める → 開発効率化につながる
人間関係の構築には時間がかかるため、褒めることを支援し開発効率化を目指す。

課題
- 褒めあい 
- 初対面の人だと褒めるハードルが高い
- 褒めることが恥ずかしい

匿名で手軽に相手を褒めることができるBot、ホメとくを開発しました。

**Comment by tkeita1024** [comment]
使用技術
Slack, Bolt, ngrok, python, MySQL, GitHub
頑張ったことをいう。

**Comment by tkeita1024** [comment]
作品の紹介
- 動画
- デモ

**Comment by tkeita1024** [comment]
アピールポイント(機能)
- 匿名で褒めたい人を褒められる
- 褒めたい度を入力できる
- 月間で褒めれた人が表彰される

**Comment by tkeita1024** [comment]
今作業しているスライド
https://docs.google.com/presentation/d/1E-x9hyilv0rq_wTsGbll0O8KDQ9uJvkFkFMR8hxc0g0/edit?usp=sharing

**Comment by tkeita1024** [comment]
とりあえずスライドver0.2です。
あとやることは、隠しスライドとデモの部分です。
https://drive.google.com/file/d/1tYlR0t5H9VF0cF90qwzrlcFeK2IQ46H4/view?usp=sharing

**Comment by tkeita1024** [comment]
デモ以外はとりあえず完成
https://drive.google.com/file/d/1QLOYyTp2ZkzrwMF2IdFys89v3i-9vcpi/view?usp=sharing

**Comment by KenSato0527** [comment]
https://docs.google.com/presentation/d/1rma-4fDNjVkG9htI5yMbbt2ryckZBONcv_8WFbjggzQ/edit?usp=sharing

原稿コメントつき

**Comment by tkeita1024** [comment]
https://drive.google.com/file/d/1DsHZfVa4j14QP3bCti6VAQwfBmIMA9Dh/view?usp=sharing

**Comment by Kai-Moriuchi** [comment]
自己紹介スライド
https://www.dropbox.com/s/miblgb116gfn8bl/%E3%83%8F%E3%83%83%E3%82%AB%E3%82%BD%E3%83%B3%E7%99%BA%E8%A1%A8%E3%82%B9%E3%83%A9%E3%82%A4%E3%83%89_%E8%87%AA%E5%B7%B1%E7%B4%B9%E4%BB%8B_Kai.pdf?dl=0

**Comment by Kai-Moriuchi** [comment]
自己紹介スライド
https://www.dropbox.com/s/oe47iyuece5y5ga/%E3%83%8F%E3%83%83%E3%82%AB%E3%82%BD%E3%83%B3%E7%99%BA%E8%A1%A8%E3%82%B9%E3%83%A9%E3%82%A4%E3%83%89_%E8%87%AA%E5%B7%B1%E7%B4%B9%E4%BB%8B_Kai.pptx?dl=0

**Comment by tkeita1024** [comment]
https://drive.google.com/file/d/1SOA4xfUhm0sDT6oACeSsYboRIxOciDNg/view?usp=sharing

**Comment by tkeita1024** [comment]
特長と褒めたい度のスライドを更新
https://drive.google.com/file/d/1UDrJ2QBR4ngiZTNQ5F4ta14r5xeLMPK5/view?usp=sharing

**Comment by Kai-Moriuchi** [comment]
やりたかった事
https://www.dropbox.com/s/c1w33ygaojbx5mx/%E3%83%8F%E3%83%83%E3%82%AB%E3%82%BD%E3%83%B3%E7%99%BA%E8%A1%A8%E3%82%B9%E3%83%A9%E3%82%A4%E3%83%89_kai.pptx?dl=0

**Comment by tkeita1024** [comment]
表記揺れを修正(p.26)
https://drive.google.com/file/d/1B6DE1qEuQAUDj_HLAvG_ZE-hTWcltWfo/view?usp=sharing

**Comment by tkeita1024** [comment]
利用技術修正、特長修正
https://drive.google.com/file/d/1yBJ24N4v9fanX9IlyO57Bj8IeUYNf0jI/view?usp=sharing

**Comment by tkeita1024** [comment]
メッセージの投稿機能を追加、最後の文言を中央寄せに修正

https://drive.google.com/file/d/1wxGozmmx5Yco28uuEmeesphrhcajlvaR/view?usp=sharing

**Comment by Kai-Moriuchi** [comment]
オリジナルメッセージスライドの作成とやりたかったことの修正
https://www.dropbox.com/s/4w1tryx31tlsjfu/%E3%83%8F%E3%83%83%E3%82%AB%E3%82%BD%E3%83%B3%E7%99%BA%E8%A1%A8%E3%82%B9%E3%83%A9%E3%82%A4%E3%83%89_ver0.5_kai.pptx?dl=0
