### ISSUE TITLE
SlcakにSlackBotで表示するメッセージをJsonで送る

### ISSUE THREAD

**Issue by tkeita1024** [b1017173/Hometoku#6]
**作ろうとしている機能の詳細**
ゴール： SlcakにSlackBotで表示するメッセージをJsonで送る
プロセス： 
1. パリティチェッされたJsonから、SlackBotで表示するメッセージに必要なデータを抽出する。
2. pythonでjsonに整形する方法を調べる。
2. Jsonに再整形する。
3. 再整形したJsonをSlackに送ることができるようにする。

**完成の定義**
バグの精査(入り込みそうなバグ)： 
1. Modalに入力された値がJsonに反映されている。
2. Slack Botで表示されるメッセージに必要な情報がJsonに含まれている。
3. 必要以外の情報は含まれていない。
2. Slackで受け取れているか確認する。

**見積もり**
[1日]  

**その他**
***作業ブランチ***
main - develop - issue06
***特筆事項***

****タスク作成者への注意事項****
1. タグ管理をしっかりやってほしいです。上のタスクを例にとると："優先度B", "feat(or 機能)", "search(or 検索)", "form(or 入力フォーム)"くらいは最低限つけてほしい。  
2. このカードの存在を忘れないで(T . T)  
    作ったタスクは移動すべきタイミングでカラムを移動し、最後まで見守りましょう。
3. 作業ブランチを切って，ブランチ名はイシュー名にする．
    ex)issue23 , issue33 とか

**Comment by Kai-Moriuchi** [comment]
Hometoku/dataの中にパリティチェックされたJsonファイルが入ってると仮定して進める

### やること
SlackAppが話す内容を送る
とりあえずメンションは後回しで
say()を使う https://slack.dev/bolt-python/ja-jp/concepts

リファレンスに沿ってメッセージを表示させる
Event Subscription -> Subscribe to Bot Eventsで
message.XXを全て追加

関数がよばれたタイミングでsay()を動かす

**Comment by Kai-Moriuchi** [comment]
以下のように構造と変数名が固定ならデータの抽出はできた
https://github.com/b1017173/Hometoku/issues/1#issuecomment-863115967

でもコードきもいからリファクタリングする
やっぱ時間ないから後回し
（オブジェクト指向忘れたなんて言えない．．．．．）
拡張性が低すぎてやっばい

**Comment by Kai-Moriuchi** [comment]
### メソッドに関して
def XXX -> None:
返り値がないことを表す
このほかにも
->str
->int
->dict
などがある．ただし，ただの注釈であって指定した型以外の形のものが返ってくることもある．

### ファイルアクセスに関して
withを用いることでclose()を記述しなくて済む

### Jsonの読み書き
#### dumpとdumpsの違い
dump：dict型をJson形式でファイルに出力
dumps：dict型を文字列に変換
https://nashiza-blog.com/2020/08/16/python-json/

### 受信したJsonで必要な要素
homePeople/.../selected_users　-> list型
homeMove/.../value -> str型

**Comment by Kai-Moriuchi** [comment]
### SlackにJsonを送る
これってchat.postMessageに沿ったJsonで送らんといけん感じ？
https://api.slack.com/methods/chat.postMessage
それだったらやばくね．イシューたてたやつ何考えてんの
そもそもJsonファイルで送るのが適していない？
Json形式で送るから，わざわざファイルに書き込まなくていいのかも（rewuestsを使うなら）
https://dev.classmethod.jp/articles/serverless-framework-slack-api-launch-01/
https://qiita.com/sqrtxx/items/49beaa3795925e7de666

Bolt調べるべ

**Comment by Kai-Moriuchi** [comment]
**channel_IDについて**

- 現在はグローバルショートカットを利用しているのでユーザはどこでもmodalを呼ぶことができる(channel_IDの検出が難しい)
- チャンネルごとにショートカットを設定するのは難しそう（アプリがいるチャンネルでのみショートカットを表示させる）
- modalに入力された「ほメッセージ」をSlack上で表示させるにはchannel_IDが必要だが上記のことが厳しいので，どこのチャンネルに表示させるかの判断ができない（複数のチャンネルにホメトクが存在している前提で）
- 対処法としては以下の4つが挙げられる
　　1. modalで送信先のチャンネルを指定してもらう
　　2. ひとつのチャンネルでのみホメトクを組み込める仕様にする
　　3. ユーザがショートカットを起動したチャンネルに送信する
　　4. スラッシュ/メッセージコマンドでmodalを表示するようにする

↓チャンネルリストのBlock elements(でもアプリがいないチャンネルもリストに表示される)
```
{
			"type": "section",
			"block_id": "section678",
			"text": {
				"type": "mrkdwn",
				"text": "Pick channels from the list"
			},
			"accessory": {
				"action_id": "text1234",
				"type": "multi_channels_select",
				"placeholder": {
					"type": "plain_text",
					"text": "Select channels"
				}
			}
		}
```
このJsonを使うならパリティチェックが必要になる（ホメトクが組み込まれているチャンネルが指定されているかどうか）
参考：https://api.slack.com/reference/block-kit/block-elements#channel_multi_select
チャンネルが選択された時点でチェックをするような動きを実装したい
`initial_channels`で選択できるチャンネルを指定できるオプション？

**複数チャンネルへの送信について**

- channel_IDをリストで受けとってfor文内で送信用の関数をリスト分回す
- 懸念点としてラグが発生する可能性がある

**Comment by Kai-Moriuchi** [comment]
**ひとつのチャンネルでのみホメトクを組み込める仕様について**
やりたいこと
1. ホメトクをチャンネルに組み込む場合に他のチャンネルに既に組み込まれているかどうかを検知する
2. 既に組み込まれているならエラーメッセージを，そうでなければそのまま組み込ませる

必要なこと

- 各channel_ID？
- 各チャンネルのUse_ID（アプリがいるかどうかを判断）

わかったこと
- [conversations.list](https://api.slack.com/methods/conversations.list)でプライベート，パブリックチャンネルのリストを取得可能
- スコープはchannels:read と groups:read が必要
- member_joined_channel でチャンネルにユーザーが入ってきたことがわかる

**Comment by Kai-Moriuchi** [comment]
**ユーザがショートカットを起動したチャンネルに送信する**

**Comment by Kai-Moriuchi** [comment]
**スラッシュ/メッセージコマンドでmodalを表示するようにする**

- スラッシュ/メッセージコマンドは必ずチャンネル内で実行される→channel_IDの取得が楽そう
- 実行されたチャンネルでメッセージを表示させる

参考になりそう
https://qiita.com/seratch/items/ed29acd565af36e65072

**Comment by Kai-Moriuchi** [comment]
**ひとつのチャンネルでのみホメトクを組み込める仕様に変更**
