### ISSUE TITLE
アーキテクチャの検討

### ISSUE THREAD

**Issue by b1017173** [b1017173/Hometoku#7]
**作ろうとしている機能の詳細**
ゴール： Hometokuのアーキテクチャを確定する
プロセス： 
1. 周辺サービスの役割を理解する
  - Slack
  - Slack api
  - Bolt
  - ngrok
  - Slack Block Kit
2. 必要なサービスを理解する
  - ユーザデータの保存場所
    - データサーバー
    - ローカルサーバー
    - ファイルサーバー
    - Cloudサービス
  - そことの通信方法
    - Flask
  - サーバー側の管理方法
    - SQL
    - MySQL
3. 処理のフローを理解する
  - ユーザの入力から出力まで

**見積もり**
120 m/人  

**その他**
***作業ブランチ***
なし
***特筆事項***
知見はコメントで共有する

****タスク作成者への注意事項****
1. タグ管理をしっかりやってほしいです。上のタスクを例にとると："優先度B", "feat(or 機能)", "search(or 検索)", "form(or 入力フォーム)"くらいは最低限つけてほしい。  
2. このカードの存在を忘れないで(T . T)  
    作ったタスクは移動すべきタイミングでカラムを移動し、最後まで見守りましょう。
3. 作業ブランチを切って，ブランチ名はイシュー名にする．
    ex)issue23 , issue33 とか

**Comment by KenSato0527** [comment]
https://kitsune.blog/ap-server-summary
APサーバとwebサーバの違い

**Comment by tkeita1024** [comment]
https://stackoverflow.com/questions/936197/what-is-the-difference-between-application-server-and-web-server
APサーバとwebサーバの違い

**Comment by Kai-Moriuchi** [comment]
https://www.rworks.jp/system/system-column/sys-entry/16259/
サーバとは

https://www.biz.ne.jp/matome/2004479/
APサーバとは

**Comment by Kai-Moriuchi** [comment]
ngrock

> これを使うことで、例えば以下のようなことを簡単に行うことができ、開発効率が非常に良くなります。
作成中のアプリケーションを友達に見てもらう（デザインチェックをしてもらう）
LineBotなどのWebhook系開発の接続テスト（ローカルのサーバーとつなぐ）
ハッカソンなどでの結果発表で、一時的にデモを外部公開する
わざわざサーバーにアプリケーションをデプロイする必要がないので、非常に楽チンです。

https://www.yoheim.net/blog.php?q=20170303

**Comment by tkeita1024** [comment]
ngrok 補足説明

GitHubやVSCodeなどのような開発を効率化するために必要なもの。具体的には、上記のようにローカルサーバーを外部からも接続できるようになるので、接続テストが非常に容易になる。

**Comment by b1017173** [comment]
フロント：Slack
APサーバ：Python，Slack api，Bolt
DB：MySQL，(余力があればAWSへ移行)
ツール：GitHub，ngrok，Slack Block Kit Builder
で，とりあえず頑張る！

**Comment by b1017173** [comment]
![image](https://user-images.githubusercontent.com/43740965/122372005-489c1080-cf9b-11eb-95f2-baa5220375e4.png)
