### ISSUE TITLE
MySQLの設計

### ISSUE THREAD

**Issue by b1017173** [b1017173/Hometoku#9]
**作ろうとしている機能の詳細**
ゴール： サービスに必要なデータを管理するテーブルの設計
プロセス： 
1. サービスに必要なデータを羅列する
2. テーブル設計のノウハウを学ぶ
3. テーブルを設計し，Excelとか見やすいものにまとめる
4. SQLでテーブルを表現する

**完成の定義**
バグの精査(入り込みそうなバグ)： 
1. データの整合性がとれない
2. セキュリティの設定がない

**見積もり**
2 d / 人  

**その他**
***作業ブランチ***
main - develop - issue09
***特筆事項***

****タスク作成者への注意事項****
1. タグ管理をしっかりやってほしいです。上のタスクを例にとると："優先度B", "feat(or 機能)", "search(or 検索)", "form(or 入力フォーム)"くらいは最低限つけてほしい。  
2. このカードの存在を忘れないで(T . T)  
    作ったタスクは移動すべきタイミングでカラムを移動し、最後まで見守りましょう。
3. 作業ブランチを切って，ブランチ名はイシュー名にする．
    ex)issue23 , issue33 とか

**Comment by KenSato0527** [comment]
使いそうなデータ

1. タイムスタンプ
2. 褒めた人
3. 褒められた人
4. 内容
5. 褒めたい度
6. ワークスペース識別ID
7. チャンネル識別ID
8. その他(プライマリキー)

**Comment by KenSato0527** [comment]
テーブル構成

テーブル1
投稿番号 | 褒めた人 | 褒められた人 | 内容 | ほめたい度 | タイムスタンプ | ワークスペースID|

テーブル2
ワークスペースID | チャンネルID

チャンネルに追加されたときにワークスペースIDとチャンネルIDのテーブルにレコード追加予定

**Comment by KenSato0527** [comment]
mysqlの環境構築
https://www.youtube.com/watch?v=mzDEHCVl6XE
(workbenchはもう少しターミナルで使えるようになってから使おうかと思っている)

mysql起動中にターミナルに書き入力で起動
mysql -u root -p
パソコンのパスワード入れてね

**Comment by KenSato0527** [comment]
<img width="698" alt="スクリーンショット 2021-06-21 18 28 46" src="https://user-images.githubusercontent.com/50400555/122742301-c4aa9700-d2c0-11eb-9470-8b8a1b3ba1f0.png">

テーブル名はまだ未定

**Comment by KenSato0527** [comment]
<img width="1050" alt="スクリーンショット 2021-06-21 20 26 39" src="https://user-images.githubusercontent.com/50400555/122754821-1823e180-d2cf-11eb-93b4-8aea2230de86.png">

**Comment by KenSato0527** [comment]
レコードを長くするか，短くしてテーブル分けするかのお話
処理が早くてメンテナンスがしやすいのはどっち？

**Comment by tkeita1024** [comment]
こんな感じで考えた。
<img width="1205" alt="スクリーンショット 2021-06-21 23 10 16" src="https://user-images.githubusercontent.com/50400490/122776260-e8cc9f00-d2e5-11eb-9cb9-0d0c47339974.png">

**Comment by tkeita1024** [comment]
悩んでいること
ワークスペース内に2つ以上のチャンネルにホメとくBotがいる時
その中に、同じ人が所属していてほめられた回数をどうするか。

話し合った結果　→    複数の合計

**Comment by tkeita1024** [comment]
データベースで扱うデー扱うデータは以下の通り
<img width="738" alt="スクリーンショット 2021-06-22 22 34 45" src="https://user-images.githubusercontent.com/50400490/122933958-0ebb7780-d3aa-11eb-8d49-1510315f066f.png">

**Comment by tkeita1024** [comment]
channelに複数所属する場合は、channel_idに書く必要がある。
しかし、複数書いてはいけないらしい...

SQLのアンチパターンという本で言われているらしい。
<img width="745" alt="スクリーンショット 2021-06-22 22 39 50" src="https://user-images.githubusercontent.com/50400490/122934861-da948680-d3aa-11eb-8bff-a9bf68645f4e.png">

こういうテーブルはダメよ

**Comment by tkeita1024** [comment]
とりあえずこんな感じで実装するぞい
<img width="366" alt="スクリーンショット 2021-06-22 23 19 08" src="https://user-images.githubusercontent.com/50400490/122941382-4decc700-d3b0-11eb-9131-f9e8304a431c.png">

**Comment by tkeita1024** [comment]
三項になったサイト
https://tepppei.hatenablog.com/entry/2020/07/25/230828

**Comment by tkeita1024** [comment]
現状書いているコード
> ```
> import mysql.connector
> 
> def accessMysql(user_id, target_id_list, workspase_id, channel_id):
>     _h = [user_id, target_id_list, workspase_id, channel_id]
>     #_user_id  = user_id
>     #_target_id_list = target_id_list
>     #_workspace_id = workspase_id
>     #_channel_id = channel_id
> 
>     _user_id = "Keita"
>     _target_id_list = ["DGGG", "FKGOP"]
>     _workspace_id = "FHKFOKK"
>     _channel_id = "DFIIPO"
> 
> # コネクションの作成
>     _conn = mysql.connector.connect(
>         host='localhost',
>         port='3306',
>         user='hometoku',
>         password='vPZrDNYjLfsV',
>         database='hometoku'
>     )
> 
>     # コネクションが切れた時に再接続してくれるよう設定
>     _conn.ping(reconnect=True)
> 
>     # 接続できているかどうか確認
>     print(_conn.is_connected())
> 
>     # DB操作用にカーソルを作成
>     _cur = _conn.cursor(buffered=True)
> 
>     # usersテーブルの作成 ： ユーザーID、ほめられた回数、ワークスペースのIDを管理する #
>     _cur.execute("""CREATE TABLE IF NOT EXISTS `users` (
>       `id` int(11) NOT NULL AUTO_INCREMENT,
>       `user_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
>       `price` int(11) NOT NULL DEFAULT 0,
>       `workspace_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
>       PRIMARY KEY (id)
>     ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci""")
> 
>     # channelsテーブルの作成 ： チャンネルIDを管理する#
>     _cur.execute("""CREATE TABLE IF NOT EXISTS `channels` (
>       `channel_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
>       PRIMARY KEY (channel_id)
>     ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci""")
> 
>     # belongsテーブルの作成 ： usersのユーザーが所属しているチャンネルを紐づけて管理する #
>     _cur.execute("""CREATE TABLE IF NOT EXISTS `belongs` (
>       `id` int(11) NOT NULL,
>       `channel_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
>       PRIMARY KEY (id, channel_id),
>       FOREIGN KEY (id) REFERENCES users(id),
>       FOREIGN KEY (channel_id) REFERENCES channels(channel_id) ON UPDATE CASCADE
>     ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci""")
> 
>     # MySQLに登録する
>     try:
>         #usersテーブルとbelongsテーブルの中でidが同じものを内部結合する。
>         _insert_sql = "select u.id, u.user_id, u.workspace_id, b.channel_id from users u INNER join belongs b on u.id = b.id;"
>         _cur.execute(_insert_sql)
>         #内部結合されたデータを全て取得#
>         _rows = _cur.fetchall()
> 
>         #初回の挿入#
>         if len(_rows) == 0:
>             _cur.execute("INSERT INTO channels (channel_id) VALUES (%s)", (_channel_id,))
>             _cur.execute("INSERT INTO users (user_id, price, workspace_id) VALUES (%s, %s, %s)", (_user_id, 0, _workspace_id))
>             _id = _cur.lastrowid
>             _cur.execute("INSERT INTO belongs (id, channel_id) VALUES (%s, %s)", (_id, _channel_id))
>             print("データの挿入に成功したよ1")
>             _conn.commit()
> 
>         #それ以降の挿入#
>         else:
>               # 内部結合されたデータをデータの長さだけ回す #
>             for _row in _rows:
>                 _row_user_id = _row[1]      # usersのuser_idを格納する
>                 _row_workspace_id = _row[2] # usersのworkspace_idを格納する
>                 _row_channel_id = _row[3]   # belongsのchannel_idを格納する
> 
>                   #内部結合されたデータとモーダルに送られた情報をそれぞれ比較し、全て同じ以外の場合に以下の処理を行う#
>                 if((_row_user_id != _user_id) or (_row_workspace_id != _workspace_id) or (_row_channel_id != _channel_id)):
>                       # channelsテーブルに存在しない場合は、channelsテーブルにチャンネルIDを追加#
>                     if _cur.execute("select exists (select * from channels where = "+ _row_channel_id +");") != 1 :
>                           _cur.execute("INSERT INTO channels (channel_id) VALUES (%s)", (_channel_id,))
>                       # userIDが異なる場合 #
>                     elif ("select exists (select * from users where = "+ _row_user_id +");") != 1 :
>                           _cur.execute("INSERT INTO users (user_id, price, workspace_id) VALUES (%s, %s, %s)", (_user_id, 0, _workspace_id))
>                       # ワークスペースIDが異なる場合 #
>                     elif ("select exists (select * from users where = "+ _row_workspace_id +");") != 1 :
>                           _cur.execute("INSERT INTO users (user_id, price, workspace_id) VALUES (%s, %s, %s)", (_user_id, 0, _workspace_id))
>                     _cur.execute("select * from users order by id desc limit 1;")
>                     _last_row = _cur.fetchone()
>                     _id = _last_row[0]
>                     _cur.execute("INSERT INTO belongs (id, channel_id) VALUES (%s, %s)", (_id, _channel_id))
>                     _conn.commit()
> 
>     except mysql.connector.errors.IntegrityError:
>         print("挿入する情報が重複しています。")
>     print("データは挿入されなかった")
> 
>     # DB操作が終わったらカーソルとコネクションを閉じる
>     _cur.close()
>     _conn.close()
> 
> accessMysql(1, 2, 3,4)``
> ```

**Comment by tkeita1024** [comment]
現状のエラー
> Traceback (most recent call last):
>   File "/Users/keita1024/development/Hackthon/Hometoku/src/connect_mysql.py", line 103, in <module>
>     accessMysql(1, 2, 3,4)
>   File "/Users/keita1024/development/Hackthon/Hometoku/src/connect_mysql.py", line 81, in accessMysql
>     if _cur.execute("select exists (select * from channels where = "+ _row_channel_id +");") != 1 :
>   File "/Users/keita1024/development/Hackthon/Hometoku/.venv/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 269, in execute
>     result = self._cnx.cmd_query(stmt, raw=self._raw,
>   File "/Users/keita1024/development/Hackthon/Hometoku/.venv/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 510, in cmd_query
>     raise errors.get_mysql_exception(exc.errno, msg=exc.msg,
> mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '= DEJEKO)' at line 1
> (.venv) keita1024@MacBook-Pro Hometoku % 
> 
> >

**Comment by tkeita1024** [comment]
SQL文を実行する際の文字列の中に存在する変数がエラーを起こしているみたい...

**Comment by tkeita1024** [comment]
これでなぜエラー文出るかのかきもい
<img width="1043" alt="スクリーンショット 2021-06-24 4 13 15" src="https://user-images.githubusercontent.com/50400490/123155061-9684ad00-d4a2-11eb-8273-5142076e8ebe.png">

**Comment by tkeita1024** [comment]
Userテーブルは、ユーザーのID、ワークスペースID、褒められた回数をなどを記録したテーブル
<img width="255" alt="スクリーンショット 2021-06-26 21 26 11" src="https://user-images.githubusercontent.com/50400490/123512959-48032880-d6c5-11eb-90c6-2f49b37ed74e.png">

Channelsテーブルは、ワークスペースID、チャンネルIDを記録したテーブル
<img width="223" alt="スクリーンショット 2021-06-26 21 26 23" src="https://user-images.githubusercontent.com/50400490/123512955-46396500-d6c5-11eb-8704-e7e29fba9f70.png">

**Comment by tkeita1024** [comment]
参考にした
https://basicincome30.com/python3-mysql-connector
